### ISSUE TITLE
Looking for an R Journal reviewer

### ISSUE THREAD

**Issue by lawremi** [aurora-mareviv/Rstarters#1]
Dear "mareviv", 

I'm looking for a reviewer for an R Journal article. I couldn't find your contact information anywhere, but from your previous blog posts, you would be an ideal reviewer for one of our submissions. My email is just my github user name @ gmail.com. Thanks and sorry for abusing this issue tracker!

Michael Lawrence
Associate Editor

**Comment by aurora-mareviv** [comment]
I apologize for the inappropriate delay in detecting this issue. I have sent you an email

**Comment by lawremi** [comment]
Thanks for the response. Hopefully you can contribute to the journal in the future.
